### ISSUE TITLE
Feature: homebrew

### ISSUE THREAD

**Issue by Fischmuetze** [Lakr233/NotchDrop#18]
By any chance to put it in the homebrew repositories?

**Comment by Lakr233** [comment]
Was trying to but too much for me to figure it out how. If you would like to do it, I can invite you to the repo.

**Comment by Mrered** [comment]
Done! https://github.com/Brewforge/homebrew-extras/commit/217bbf24561d6ac871db355866c42c3c73f24f73

```sh
brew tap brewforge/extras
brew install --cask notchdrop
```

**Comment by Fischmuetze** [comment]
very cool - thank you Von meinem iPhone gesendetAm 24.07.2024 um 07:32 schrieb Mrered Cio ***@***.***>:﻿
Done! ***@***.***
brew tap brewforge/extras
brew install --cask notchdrop

**Comment by Mrered** [comment]
https://github.com/Brewforge/homebrew-extras/issues/159

**Comment by Lakr233** [comment]
@Mrered would you like to submit this app into the official homebrew repo? I can help if you would like to!

**Comment by Mrered** [comment]
@Lakr233 If you intend to publish the Ruby file to the official Homebrew repo, I have no objections. You are welcome to reference the file I have written. However, since official script publication needs to pass the review of the repo bots, and as the official bots evolves, I cannot guarantee that my Ruby file will always pass the official repo bot's review. Therefore, the Ruby file for the official repository need to be published and maintained by you personally.

**Comment by Lakr233** [comment]
I understand. I think I'm going to stop here. Thansk :)

**Comment by Mrered** [comment]
感谢作者的软件，我们是 BrewForge ，致力于收录各种还没有支持 Homebrew 安装方式的（仓库参与者们觉得）有用的软件和大家推荐的软件，主要面向默认使用简体中文开发的软件，也包括其他语言的软件。如果您也愿意一起为开源项目做贡献，可以了解一下我们的两个仓库。感谢！😊

**Comment by Fischmuetze** [comment]
In my opinion, this is not necessary. It is quite normal for many apps to offer this via a private tap, as you have doneVon meinem iPhone gesendetAm 24.07.2024 um 08:30 schrieb Lakr ***@***.***>:﻿
@Mrered would you like to submit this app into the official homebrew repo? I can help if you would like to!
